sudo: false

language: node_js
node_js:
  - "stable"
services:
  - mongodb
env:
  - port=3000
  - JWT_KEY=SECRET
script:
  - npm ci
  - npm run coverage

deploy:
  github-token: $GITHUB_TOKEN
notifications:
  email: false
after_success:
  - npm run test:coveralls